# Generated by Django 3.0.4 on 2020-11-14 09:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='history_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='realestate',
            name='last_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Last price'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='url',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
