# Generated by Django 3.0.4 on 2020-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20201114_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
