# Generated by Django 3.0.4 on 2020-11-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_realestate_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ['-updated']},
        ),
    ]
